CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AspNetRoles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" uuid NOT NULL,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    "DateOfBirth" timestamp with time zone NOT NULL,
    "DriverLicenseNumber" character varying(20),
    "DriverLicenseExpiry" timestamp with time zone,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "Cars" (
    "Id" uuid NOT NULL,
    "Brand" character varying(50) NOT NULL,
    "Model" character varying(50) NOT NULL,
    "Year" integer NOT NULL,
    "Color" character varying(30) NOT NULL,
    "VIN" character varying(17) NOT NULL,
    "LicensePlate" character varying(15) NOT NULL,
    "PricePerDay" numeric(18,2) NOT NULL,
    "PricePerHour" numeric(18,2) NOT NULL,
    "IsAvailable" boolean NOT NULL,
    "ImageUrl" text,
    "Description" character varying(1000) NOT NULL,
    "Class" integer NOT NULL,
    "Transmission" integer NOT NULL,
    "FuelType" integer NOT NULL,
    "Seats" integer NOT NULL,
    "EngineCapacity" double precision NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Cars" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Documents" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Type" integer NOT NULL,
    "FileName" character varying(255) NOT NULL,
    "FilePath" character varying(500) NOT NULL,
    "FileSize" bigint NOT NULL,
    "Description" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Documents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Documents_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Bookings" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "CarId" uuid NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "TotalPrice" numeric(18,2) NOT NULL,
    "Status" integer NOT NULL,
    "Notes" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Bookings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Bookings_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Bookings_Cars_CarId" FOREIGN KEY ("CarId") REFERENCES "Cars" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_Bookings_CarId" ON "Bookings" ("CarId");

CREATE INDEX "IX_Bookings_UserId" ON "Bookings" ("UserId");

CREATE INDEX "IX_Documents_UserId" ON "Documents" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251110180720_InitialCreate', '8.0.0');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251110211858_SeedData', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "AspNetUsers" RENAME COLUMN "DateOfBirth" TO "RegistrationDate";

ALTER TABLE "AspNetUsers" ADD "BirthDate" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "AspNetUsers" ADD "DrivingExperience" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251129180550_AddUserExtendedProperties', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Documents" DROP COLUMN "FileSize";

ALTER TABLE "Documents" RENAME COLUMN "Type" TO "DocumentType";

ALTER TABLE "Documents" ADD "Status" text NOT NULL DEFAULT '';

ALTER TABLE "Documents" ADD "VerifiedAt" timestamp with time zone;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251207212810_InitialCreate1', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Cars" DROP COLUMN "LicensePlate";

ALTER TABLE "Cars" DROP COLUMN "PricePerHour";

ALTER TABLE "Cars" DROP COLUMN "VIN";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251211061229_RemoveVINLicensePlatePricePerHour', '8.0.0');

COMMIT;

START TRANSACTION;

CREATE TABLE "Banners" (
    "Id" uuid NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Description" character varying(500),
    "ImageUrl" character varying(500) NOT NULL,
    "Link" character varying(200),
    "DisplayOrder" integer NOT NULL DEFAULT 0,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "StartDate" timestamp with time zone,
    "EndDate" timestamp with time zone,
    "ButtonText" character varying(50),
    "BannerType" integer NOT NULL DEFAULT 1,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Banners" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_Banners_BannerType" ON "Banners" ("BannerType");

CREATE INDEX "IX_Banners_DisplayOrder" ON "Banners" ("DisplayOrder");

CREATE INDEX "IX_Banners_IsActive" ON "Banners" ("IsActive");

CREATE INDEX "IX_Banners_IsActive_BannerType_DisplayOrder" ON "Banners" ("IsActive", "BannerType", "DisplayOrder");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251214141019_AddBannersTable', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "AspNetUsers" ADD "EmailConfirmationToken" text;

ALTER TABLE "AspNetUsers" ADD "EmailConfirmationTokenExpiry" timestamp with time zone;

ALTER TABLE "AspNetUsers" ADD "PasswordResetToken" text;

ALTER TABLE "AspNetUsers" ADD "PasswordResetTokenExpiry" timestamp with time zone;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251215070730_AddEmailConfirmationFields', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "AspNetUsers" ADD "EmailConfirmationCode" text;

ALTER TABLE "AspNetUsers" ADD "EmailConfirmationCodeExpiry" timestamp with time zone;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251215123149_AddEmailConfirmationCodeFields', '8.0.0');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251215125745_AddEmailConfirmationCodeFields2', '8.0.0');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251215130246_AddEmailConfirmationCodeFields3', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "AspNetUsers" ADD "PasswordResetCode" text;

ALTER TABLE "AspNetUsers" ADD "PasswordResetCodeExpiry" timestamp with time zone;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251215155507_AddEmailConfirmationCodeFields4', '8.0.0');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260124100808_InitialCreateNEWdb', '8.0.0');

COMMIT;

START TRANSACTION;

CREATE TABLE "Chats" (
    "Id" uuid NOT NULL,
    "UserId" uuid,
    "TempUserId" uuid,
    "TempUserName" character varying(100),
    "TempUserEmail" character varying(100),
    "TempUserPhone" character varying(20),
    "Topic" character varying(200) NOT NULL,
    "Status" integer NOT NULL,
    "UnreadCount" integer NOT NULL,
    "LastMessageAt" timestamp with time zone,
    "LastAdminResponseAt" timestamp with time zone,
    "TempUserExpiry" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Chats" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Chats_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL
);

CREATE TABLE "ChatMessages" (
    "Id" uuid NOT NULL,
    "ChatId" uuid NOT NULL,
    "Message" text NOT NULL,
    "MessageType" integer NOT NULL,
    "SenderUserId" uuid,
    "SenderAdminId" uuid,
    "IsRead" boolean NOT NULL,
    "ReadAt" timestamp with time zone,
    "AttachmentUrl" character varying(500),
    "AttachmentType" character varying(50),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_ChatMessages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChatMessages_AspNetUsers_SenderAdminId" FOREIGN KEY ("SenderAdminId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_ChatMessages_AspNetUsers_SenderUserId" FOREIGN KEY ("SenderUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_ChatMessages_Chats_ChatId" FOREIGN KEY ("ChatId") REFERENCES "Chats" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ChatMessages_ChatId" ON "ChatMessages" ("ChatId");

CREATE INDEX "IX_ChatMessages_CreatedAt" ON "ChatMessages" ("CreatedAt");

CREATE INDEX "IX_ChatMessages_IsRead" ON "ChatMessages" ("IsRead");

CREATE INDEX "IX_ChatMessages_MessageType" ON "ChatMessages" ("MessageType");

CREATE INDEX "IX_ChatMessages_SenderAdminId" ON "ChatMessages" ("SenderAdminId");

CREATE INDEX "IX_ChatMessages_SenderUserId" ON "ChatMessages" ("SenderUserId");

CREATE INDEX "IX_Chats_LastMessageAt" ON "Chats" ("LastMessageAt");

CREATE INDEX "IX_Chats_Status" ON "Chats" ("Status");

CREATE INDEX "IX_Chats_TempUserExpiry" ON "Chats" ("TempUserExpiry");

CREATE INDEX "IX_Chats_TempUserId" ON "Chats" ("TempUserId");

CREATE INDEX "IX_Chats_UserId" ON "Chats" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260212022050_AddChatTables', '8.0.0');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260212060156_AddCascadeDeleteForChatMessages', '8.0.0');

COMMIT;

START TRANSACTION;

CREATE TABLE "Faqs" (
    "Id" uuid NOT NULL,
    "Question" character varying(500) NOT NULL,
    "Answer" text NOT NULL,
    "Category" character varying(100),
    "DisplayOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Faqs" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_Faqs_Category" ON "Faqs" ("Category");

CREATE INDEX "IX_Faqs_IsActive" ON "Faqs" ("IsActive");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260215034747_AddFaqEntity', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Banners" ADD "MediaType" integer NOT NULL DEFAULT 0;

ALTER TABLE "Banners" ADD "VideoUrl" character varying(500);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260215044802_AddVideoSupportToBanner', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Banners" ADD "VideoAutoplay" boolean NOT NULL DEFAULT TRUE;

ALTER TABLE "Banners" ADD "VideoControls" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Banners" ADD "VideoLoop" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Banners" ADD "VideoMuted" boolean NOT NULL DEFAULT TRUE;

CREATE TABLE "Pages" (
    "Id" uuid NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Slug" character varying(200) NOT NULL,
    "Content" text NOT NULL,
    "MetaDescription" character varying(300),
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "DisplayOrder" integer NOT NULL DEFAULT 0,
    "PublishedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Pages" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_Pages_IsActive" ON "Pages" ("IsActive");

CREATE UNIQUE INDEX "IX_Pages_Slug" ON "Pages" ("Slug");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260215141051_AddVideoSettingsToBanner', '8.0.0');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260215150534_AddPagesTable', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Banners" ALTER COLUMN "Title" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260215155248_MakeBannerTitleNullable', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Documents" ALTER COLUMN "Status" TYPE character varying(20);
ALTER TABLE "Documents" ALTER COLUMN "Status" SET DEFAULT 'Pending';

ALTER TABLE "Documents" ADD "BirthDate" character varying(20);

ALTER TABLE "Documents" ADD "DocumentNumber" character varying(50);

ALTER TABLE "Documents" ADD "ExpiryDate" timestamp with time zone;

ALTER TABLE "Documents" ADD "IssueDate" timestamp with time zone;

ALTER TABLE "Documents" ADD "IssuedBy" character varying(200);

ALTER TABLE "Documents" ADD "PlaceOfBirth" character varying(200);

CREATE INDEX "IX_Documents_DocumentNumber" ON "Documents" ("DocumentNumber");

CREATE INDEX "IX_Documents_Status" ON "Documents" ("Status");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260408221400_AddDocumentDetails', '8.0.0');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260408232222_AddDocumentFields', '8.0.0');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260413224042_UpdateDocumentFields', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Documents" ADD "FileName2" character varying(255);

ALTER TABLE "Documents" ADD "FilePath2" character varying(500);

ALTER TABLE "Documents" ADD "RegistrationAddress" character varying(500);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260415010242_AddSecondFileAndAddress', '8.0.0');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260415053538_AddNewPagesTable', '8.0.0');

COMMIT;

START TRANSACTION;

CREATE TABLE "CarImage" (
    "Id" uuid NOT NULL,
    "CarId" uuid NOT NULL,
    "ImageUrl" character varying(500) NOT NULL,
    "FileName" character varying(255),
    "DisplayOrder" integer NOT NULL DEFAULT 0,
    "IsMain" boolean NOT NULL DEFAULT FALSE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_CarImage" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CarImage_Cars_CarId" FOREIGN KEY ("CarId") REFERENCES "Cars" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_CarImage_CarId_DisplayOrder" ON "CarImage" ("CarId", "DisplayOrder");

CREATE INDEX "IX_CarImage_IsMain" ON "CarImage" ("IsMain");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260418004620_AddCarImages', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Bookings" ADD "ContractNumber" text;

ALTER TABLE "Bookings" ADD "ContractUrl" text;

ALTER TABLE "Bookings" ADD "DepositAmount" numeric NOT NULL DEFAULT 0.0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260419000013_AddBookingContractFields', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Cars" ADD "LicensePlate" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260419032229_AddLicensePlateToCar', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Cars" ADD "VIN" character varying(17);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260419054646_AddVINToCar', '8.0.0');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260419085657_AddUserMiddleName', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "AspNetUsers" ADD "MiddleName" character varying(50);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260419095133_Add2UserMiddleName', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Cars" ADD "Deposit" numeric(18,2) NOT NULL DEFAULT 0.0;

ALTER TABLE "Cars" ADD "MileageLimitPerDay" integer NOT NULL DEFAULT 250;

ALTER TABLE "Cars" ADD "OverMileagePricePerKm" numeric(18,2) NOT NULL DEFAULT 0.0;

ALTER TABLE "Cars" ADD "PricePerDay15" numeric(18,2) NOT NULL DEFAULT 0.0;

ALTER TABLE "Cars" ADD "PricePerDay30" numeric(18,2) NOT NULL DEFAULT 0.0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260601192521_AddNewCarFields', '8.0.0');

COMMIT;

